# Generated by Django 3.1 on 2020-08-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('nickname', models.TextField(blank=True, null=True)),
                ('real_name', models.TextField(blank=True, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('discord', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('vacation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
