# Generated by Django 3.1 on 2020-09-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClanApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'managed': True},
        ),
    ]
