# Generated by Django 3.1 on 2020-09-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClanApp', '0002_auto_20200906_2208'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='members',
            table='members',
        ),
    ]
